### ISSUE TITLE
bidirectional encoder后面的decoder

### ISSUE THREAD

**Issue by lkluo** [xueyouluo/my_seq2seq#1]
如果用biRNN， decoder的hidden_size不应该是encoder的两倍吗？我看你的code里面好像没有这样的设定，关键是code还能跑。请指正？

另外，我发现当num_layers>2 时会出错。事实上，只有当encoder的layer等于1，decoder的layer等于2的时候，code是work的。从下面的code可以看出：
fw_cell = get_rnn_cell('gru',self.dim_size,num_layers= 1, train_phase=self.train_phase, keep_prob=self.keep_prob_config)
        bw_cell = get_rnn_cell('gru',self.dim_size,num_layers= 1, train_phase=self.train_phase, keep_prob=self.keep_prob_config)
dec_cell = get_rnn_cell('gru', self.dim_size, num_layers=self.num_layers, train_phase=self.train_phase,
                                keep_prob=self.keep_prob_config)

**Comment by xueyouluo** [comment]
@lkluo 谢谢你指出的bug，确实有这个问题。 可以跑通是因为BiRNN出来是fw state 和 bw state刚好作为decoder两层layer的initial state。 如果deocder layer!=2就会出错。我会修改一下结构，将encoder出来的state过一层NN转换为decoder需要的state。同时也会改一下attention这边，只针对第一层encoder做attention_wrapper。

**Comment by lkluo** [comment]
你的model def里面，train model都是用beam search？不用会不会好一点，因为对于train stage，data认为是正确的。

**Comment by xueyouluo** [comment]
@lkluo 我更新了模型结构，可以查看readme说明。 train model的时候是不会使用beam search的，use_beam_search=False。主要是在设置attention的时候需要tile_batch，代码有点乱，过两天会整理一下代码。

**Comment by xueyouluo** [comment]
closing the issue, I have refactoring the code.
