### ISSUE TITLE
inference stage still not quite right

### ISSUE THREAD

**Issue by Jiakui** [xueyouluo/my_seq2seq#2]
The training stage converges pretty fast for some generated toy data, but the inference stage does not output correct result.

A question has been posted on stackoverflow:
https://stackoverflow.com/questions/44353824/tensorflow-seq2seq-inference-stage-wired-result

Thanks!

**Comment by lkluo** [comment]
I suspect your training data are not sufficient, and thus resulting in a overfitted model.  Try to use a large dataset for training.

**Comment by xueyouluo** [comment]
Hi @Jiakui, this is a simple model to test if the beam search works,  I didn't test this model on other dataset. As for your question, I think maybe:
- This model is simple than tf-seq2seq of google
- As for the greedy search, I think the api is correct. But for the beam search, may need more test.
- I have change the code, you may try the new code.

**Comment by xueyouluo** [comment]
@Jiakui I will close this issue. I have tested this new code on the toy data, and it turns out right.
